package view;

import java.awt.event.KeyEvent;
import tlacitka.*;

public class View extends javax.swing.JFrame {
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radek1 = new javax.swing.JTextField();
        radek2 = new javax.swing.JTextField();
        superTlacitko4 = new view.SuperTlacitko();
        superTlacitko5 = new view.SuperTlacitko(new TlacitkoDeleno(), KeyEvent.VK_DIVIDE, "/");
        superTlacitko6 = new view.SuperTlacitko(new TlacitkoKrat(), KeyEvent.VK_MULTIPLY, "*");
        superTlacitko7 = new view.SuperTlacitko(new TlacitkoMinus(), KeyEvent.VK_SUBTRACT, "-");
        superTlacitko8 = new view.SuperTlacitko();
        superTlacitko9 = new view.SuperTlacitko();
        superTlacitko10 = new view.SuperTlacitko();
        superTlacitko11 = new view.SuperTlacitko(new TlacitkoPlus(), KeyEvent.VK_ADD, "+");
        superTlacitko12 = new view.SuperTlacitko();
        superTlacitko13 = new view.SuperTlacitko();
        superTlacitko14 = new view.SuperTlacitko();
        superTlacitko15 = new view.SuperTlacitko();
        superTlacitko16 = new view.SuperTlacitko();
        superTlacitko17 = new view.SuperTlacitko();
        superTlacitko18 = new view.SuperTlacitko();
        superTlacitko19 = new view.SuperTlacitko();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        radek1.setEditable(false);
        radek1.setBackground(new java.awt.Color(255, 255, 255));

        radek2.setEditable(false);
        radek2.setBackground(new java.awt.Color(255, 255, 255));

        superTlacitko4.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko4.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko4.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko5.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko5.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko5.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko6.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko6.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko6.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko7.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko7.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko7.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko8.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko8.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko8.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko9.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko9.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko9.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko10.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko10.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko10.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko11.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko11.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko11.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko12.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko12.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko12.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko13.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko13.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko13.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko14.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko14.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko14.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko15.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko15.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko15.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko16.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko16.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko16.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko17.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko17.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko17.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko18.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko18.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko18.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko19.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko19.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko19.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(superTlacitko8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(superTlacitko9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(superTlacitko10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(superTlacitko11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(superTlacitko13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(superTlacitko17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(radek1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radek2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(superTlacitko4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(superTlacitko5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(superTlacitko6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(superTlacitko7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radek1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radek2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField radek1;
    private javax.swing.JTextField radek2;
    private view.SuperTlacitko superTlacitko10;
    private view.SuperTlacitko superTlacitko11;
    private view.SuperTlacitko superTlacitko12;
    private view.SuperTlacitko superTlacitko13;
    private view.SuperTlacitko superTlacitko14;
    private view.SuperTlacitko superTlacitko15;
    private view.SuperTlacitko superTlacitko16;
    private view.SuperTlacitko superTlacitko17;
    private view.SuperTlacitko superTlacitko18;
    private view.SuperTlacitko superTlacitko19;
    private view.SuperTlacitko superTlacitko4;
    private view.SuperTlacitko superTlacitko5;
    private view.SuperTlacitko superTlacitko6;
    private view.SuperTlacitko superTlacitko7;
    private view.SuperTlacitko superTlacitko8;
    private view.SuperTlacitko superTlacitko9;
    // End of variables declaration//GEN-END:variables
}
