package view;

import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import kalkulacka1.Model;
import tlacitka.*;

public class View extends javax.swing.JFrame implements PropertyChangeListener {
    //Vlastnosti
    private final Model mujModel;
    public View() {
        initComponents();
        mujModel = Model.getInstance();
        mujModel.addPropertyChangeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radek1 = new javax.swing.JTextField();
        radek2 = new javax.swing.JTextField();
        superTlacitko4 = new view.SuperTlacitko(new TlacitkoCE(), KeyEvent.VK_F23, "CE");
        superTlacitko5 = new view.SuperTlacitko(new TlacitkoC(), KeyEvent.VK_F24, "C");
        superTlacitko6 = new view.SuperTlacitko(new TlacitkoZpet(), KeyEvent.VK_BACK_SPACE, "<-");
        superTlacitko7 = new view.SuperTlacitko(new TlacitkoDeleno(), KeyEvent.VK_DIVIDE, "/");
        superTlacitko8 = new view.SuperTlacitko(new Tlacitko4(), KeyEvent.VK_NUMPAD4, "4");
        superTlacitko9 = new view.SuperTlacitko(new Tlacitko5(), KeyEvent.VK_NUMPAD5, "5");
        superTlacitko10 = new view.SuperTlacitko(new Tlacitko6(), KeyEvent.VK_NUMPAD6, "6");
        superTlacitko11 = new view.SuperTlacitko(new TlacitkoMinus(), KeyEvent.VK_SUBTRACT, "-");
        superTlacitko12 = new view.SuperTlacitko(new TlacitkoRovnase(), KeyEvent.VK_ENTER, "=");
        superTlacitko13 = new view.SuperTlacitko(new Tlacitko1(), KeyEvent.VK_NUMPAD1, "1");
        superTlacitko14 = new view.SuperTlacitko(new Tlacitko2(), KeyEvent.VK_NUMPAD2, "2");
        superTlacitko15 = new view.SuperTlacitko(new Tlacitko3(), KeyEvent.VK_NUMPAD3, "3");
        superTlacitko16 = new view.SuperTlacitko(new TlacitkoPlus(), KeyEvent.VK_ADD, "+");
        superTlacitko17 = new view.SuperTlacitko(new Tlacitko0(), KeyEvent.VK_NUMPAD0, "0");
        superTlacitko18 = new view.SuperTlacitko(new TlacitkoTecka(), KeyEvent.VK_DECIMAL, ".");
        superTlacitko19 = new view.SuperTlacitko(new TlacitkoAns(), KeyEvent.VK_F22, "ANS");
        superTlacitko20 = new view.SuperTlacitko(new Tlacitko7(), KeyEvent.VK_NUMPAD7, "7");
        superTlacitko21 = new view.SuperTlacitko(new Tlacitko8(), KeyEvent.VK_NUMPAD8, "8");
        superTlacitko22 = new view.SuperTlacitko(new Tlacitko9(), KeyEvent.VK_NUMPAD9, "9");
        superTlacitko23 = new view.SuperTlacitko(new TlacitkoKrat(), KeyEvent.VK_MULTIPLY, "*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        radek1.setEditable(false);
        radek1.setBackground(new java.awt.Color(255, 255, 255));

        radek2.setEditable(false);
        radek2.setBackground(new java.awt.Color(255, 255, 255));

        superTlacitko4.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko4.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko4.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko5.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko5.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko5.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko6.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko6.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko6.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko7.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko7.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko7.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko8.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko8.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko8.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko9.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko9.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko9.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko10.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko10.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko10.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko11.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko11.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko11.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko12.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko12.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko12.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko13.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko13.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko13.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko14.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko14.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko14.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko15.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko15.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko15.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko16.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko16.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko16.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko17.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko17.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko17.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko18.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko18.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko18.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko19.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko19.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko19.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko20.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko20.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko20.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko21.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko21.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko21.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko22.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko22.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko22.setPreferredSize(new java.awt.Dimension(50, 50));

        superTlacitko23.setMaximumSize(new java.awt.Dimension(50, 50));
        superTlacitko23.setMinimumSize(new java.awt.Dimension(50, 50));
        superTlacitko23.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(superTlacitko13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(superTlacitko17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(superTlacitko8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(radek1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radek2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(superTlacitko4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(superTlacitko5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(superTlacitko6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(superTlacitko7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(superTlacitko20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(superTlacitko23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radek1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radek2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superTlacitko17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superTlacitko12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField radek1;
    private javax.swing.JTextField radek2;
    private view.SuperTlacitko superTlacitko10;
    private view.SuperTlacitko superTlacitko11;
    private view.SuperTlacitko superTlacitko12;
    private view.SuperTlacitko superTlacitko13;
    private view.SuperTlacitko superTlacitko14;
    private view.SuperTlacitko superTlacitko15;
    private view.SuperTlacitko superTlacitko16;
    private view.SuperTlacitko superTlacitko17;
    private view.SuperTlacitko superTlacitko18;
    private view.SuperTlacitko superTlacitko19;
    private view.SuperTlacitko superTlacitko20;
    private view.SuperTlacitko superTlacitko21;
    private view.SuperTlacitko superTlacitko22;
    private view.SuperTlacitko superTlacitko23;
    private view.SuperTlacitko superTlacitko4;
    private view.SuperTlacitko superTlacitko5;
    private view.SuperTlacitko superTlacitko6;
    private view.SuperTlacitko superTlacitko7;
    private view.SuperTlacitko superTlacitko8;
    private view.SuperTlacitko superTlacitko9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("radek1")) radek1.setText(evt.getNewValue().toString());
        else if (evt.getPropertyName().equals("radek2")) radek2.setText(evt.getNewValue().toString());
    }
}
